Zatvobor/tirexs

lib/tirexs/elastic_search.ex, test/tirexs/config_test.exs
Replaced the config record with an URI for easier connection handling. This also adds https support.
Now you can change the default settings with options:
`settings = Tirexs.ElasticSearch.config(scheme: "https", userinfo: "user:pass")`
or with an URL:
`settings = Tirexs.ElasticSearch.config("https://user:pass@localhost:9201")`
=> Configure connection url using list or existing url

test/tirexs/logger_test.exs
Don't output logging when running unit tests.
=> Silence logging during test

.travis.yml
`MIX_ENV=test` is implied by `mix test` so is not needed.
=> Remove MIX_ENV=test when running tests

mix.exs
When depending on a package using scm hex does not automatically handle dependency resolution for that dependency. Solution is to depend only on other hex dependencies.
=> Make exjsx a hex based dependency

mix.exs
When trying to use tirexs in my project I noticed that it was depending on those two libraries at runtime. This makes sure those are available when needed.
=> Add inets and exjsx to runtime dependencies

lib/tirexs/manage.ex, test/acceptances/manage_test.exs
https://www.elastic.co/guide/en/elasticsearch/reference/2.x/indices-aliases.html
I think that needs to define aliases API in tirexs. Thanks.
=> Added Index aliases API

lib/tirexs/http.ex, test/acceptances/http_test.exs
=> Evolve `Tirexs.HTTP` interface

lib/tirexs.ex, lib/tirexs/manage.ex, lib/tirexs/resources.ex, lib/tirexs/resources/apis.ex, lib/tirexs/resources/indicies.ex, test/acceptances/manage_test.exs, test/acceptances/resources/indicies_test.exs, test/acceptances/resources_test.exs, test/tirexs/resources/indicies_test.exs, test/tirexs/resources_test.exs
According to the main ES specs, https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api and from basic reference, https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html
Index management:
Mapping Management:
Index Settings:
Status Management:
Alias management:
Monitoring:
Replica configurations:
Further scope:
_source
_count
_warmer
_percolate and .percolator
_bulk
_explain
_validate/query
`bump!` w/ `body`
```
create_resource_settings(definition, uri)
url  = "#{definition[:index]}/#{definition[:type]}/_mapping"
json = to_resource_json(definition)
HTTP.put(url, json, uri)
```
=> `Tirexs.Resources` module

lib/tirexs.ex, lib/tirexs/bulk.ex, lib/tirexs/dsl.ex, lib/tirexs/elastic_search.ex, lib/tirexs/elastic_search/settings.ex, lib/tirexs/manage.ex, lib/tirexs/mapping.ex, lib/tirexs/percolator.ex, lib/tirexs/resources.ex, lib/tirexs/resources/apis.ex, lib/tirexs/resources/indicies.ex, mix.exs, test/acceptances/bulk_test.exs, test/acceptances/examples_test.exs, test/acceptances/mapping_test.exs, test/acceptances/percolator_test.exs, test/acceptances/resources/indicies_test.exs, test/acceptances/resources_test.exs, test/acceptances/scroll_test.exs, test/acceptances/warmer_test.exs, test/tirexs/resources/indicies_test.exs, test/tirexs/resources_test.exs
Scope:
one of avalable resource helper, #182
=> `v0.8.0-beta3` release candidate

lib/tirexs/query.ex, lib/tirexs/query/logic.ex, test/tirexs/query_test.exs
Adds support for the elasticsearch [match_phrase](https://www.elastic.co/guide/en/elasticsearch/guide/current/phrase-matching.html) query
=> feat(query): add support for match_phrase

lib/tirexs/index/logic.ex, lib/tirexs/index/settings.ex, test/tirexs/index/settings_test.exs
These macros cause warnings at compile time for projects using tirexs with
Elixir 1.3. There are plenty of other warnings while compiling tirexs itself,
but I think these are higher priority.
=> Fix elixir 1.3 warnings in macros

lib/tirexs/http.ex, test/acceptances/http_test.exs, test/acceptances/resources_test.exs
This could happen when elasticsearch is down
=> Add :error pattern match for Tirexs.HTTP

lib/tirexs/query.ex, lib/tirexs/query/logic.ex, test/tirexs/query_test.exs
Hello,
I've added a `min_score` function for the function score query. 
Official documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
=> Add min_score attribute for function score

examples/mapping_with_settings.exs, lib/tirexs/mapping.ex, test/acceptances/mapping_test.exs, test/tirexs/mapping_test.exs
Hi there, I'm pretty new to Elixir, but that's a feature I really need in order to get my project running. 
Basically it allows you to add extra configuration to the index mapping like:
```
mappings dynamic: "false", _parent: [type: "parent_type"] do
```
Not sure if that's the best way to implement it, let me know if more work is needed.
=> Added support for extra mapping settings

lib/tirexs/bulk.ex, test/tirexs/bulk_test.exs
When using the Bulk API for actions like 'index' or 'create' we are not removing the set of reserved keywords (@underscored) attributes from the document, this PR just apply the 'drop_underscored()' function. Is there a reason for that? I'm not an expert on ES, so forgive me if I'm missing something.
=> remove underscore attrs when indexing/creating

lib/tirexs/query.ex, lib/tirexs/query/logic.ex, test/tirexs/query_test.exs
Adds support for the elasticsearch [span_multi](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-multi-term-query.html) query
=> add support for span_multi

lib/tirexs/elastic_search/settings.ex
According to the official documentation, we need to se `PUT` instead of `POST` for creating an index with settings. Using POST creates an error (at least in version 5.x of elastic). This solves such error
=> Use PUT instead of post for index settings

lib/tirexs/query.ex, lib/tirexs/query/logic.ex, test/tirexs/query/bool_test.exs
Hi there, 
I've added the possibility to add some parameters when you do a bool request. 
Like `minimum_should_match` or `boost`. 
What do you think ? 
cf: documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
=> Add Parameters for Bool Method

lib/tirexs/http.ex, lib/tirexs/logger.ex, mix.exs, test/tirexs/logger_test.exs
In development, it would be really handy to have CURL commands logged to the console. If a query doesn't behave the way you expect, you could just grab the CURL command and try it out.
With this PR, setting `config :tirexs, log: true` would enable this behavior.
Concerns:
+ Maybe it would be better to offer a request hooks instead? Such a feature could be useful for other scenarios as well.
+ Maybe this shouldn't be `curl`-specific? For example, it might be cool to allow users to log commands in an HTTPie format instead. Hooks would accomodate this as well.
+ Should we be using Elixir.Logger? Currently, `Tirexs.Logger.log/1` uses `:error_logger.info_msg`.
=> Log curl commands

lib/tirexs/mapping.ex
Hello, I use tirexs with ElasticSearch 5.2 and I've got a trouble with `Tirexs.Mapping`. When I tried to define `mappings` with `settings`, I got an error `No handler found for uri [/my_index] and method [POST]`. 
I've checked the documentation and [found](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/indices-create-index.html#mappings) that it should be a `PUT` request. However, [older](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/indices-create-index.html#mappings) ES versions use `POST` request to define mappings. I tried to change `POST` request to `PUT` and it works both with ES 5.2 and ES 1.4.
In this PR `settings` request has been changed to `PUT`, to provide support for newer versions of ElasticSearch.
=> Use PUT query to update indeces settings

lib/tirexs/http.ex
Fixed content-type error when deleting items from ES5.5.
HTTP module acceptance test passes now when tried locally with ES2.4 and ES5.5.
=> fixed http delete on ES5.x
